### ISSUE TITLE
add GemStone support to magritte

### ISSUE THREAD

**Issue by dalehenrich** [magritte-metamodel/magritte#105]
Basically port/update/adapt the work in https://github.com/GsDevKit/Magritte3 to the code base in this repository

**Comment by dariogithub** [comment]
About    testDefaultLabel   errors
it may be enough to move the  String normalizeCamelCase  method
from MagritteModel to Magritte-PharoX-Model
GLASS 3.4.3 define this method as a basis ( Not as an Magritte extension )

**Comment by dalehenrich** [comment]
@dariogithub I will keep that in mind ... before seeing your message I started by taking a look MASelectorAccessorTest>>testStore ... and at the moment I'm wondering about what function the `source:` method is supposed to perform:
```smalltalk
testStore
	| evaluator |
	evaluator := GRPlatform current
		magritteEvaluatorClassFor: self actualClass.
	self
		assert:
			(evaluator new
				source: self accessor storeString;
				evaluate) = self accessor
```
The [change](https://github.com/dalehenrich/magritte/commit/7012ee22f67a7e05ed6bd7734fdb0b89b144dbfb#diff-7d0cd821f9e54508f307d0e403983576R9) was made in a commit by @noha with the comment `Added pharo7 model package`, so I'm going to assume that it will be safe to move MASelectorAccessorTest>>testStore into a Pharo test package and use the original implementation in a GemStone test package ... if it isn't safe, it may be necessary to add the `pharo7 model package` to GemStone - whatever that is ...

@dariogithub could you do some research on the rationale behind [this change to the test}(https://github.com/dalehenrich/magritte/commit/7012ee22f67a7e05ed6bd7734fdb0b89b144dbfb#diff-7d0cd821f9e54508f307d0e403983576R9) and whether or not the `pharo7 model package` functionality is now required by Magritte?

I will look elsewhere for some low hanging fruit, while you check this out ...

**Comment by dariogithub** [comment]
OK.

A) The method   ( evaluator evaluate: self accessor storeString )  is AutoDeprecationRefactory into Pharo7.
It is translate by the Pharo  system compiler.
So I think we need to move the changed method into a Pharo test package  and use the original implementation in a Gemstone test package.

B) The GLASS Object storeString method create a stream based on AppendStream  which does not implement  the   store:    method.

The method     store:    is call  from  MAAccessor and relative subclasses    storeOn:   method

Solutions?

**Comment by dariogithub** [comment]
@dariogithub could you do some research on the rationale behind this change to the test and whether or not the pharo7 model package functionality is now required by Magritte?

sorry but I realize now that you didn't understand your request.
I try to see the question.

**Comment by dariogithub** [comment]
.... sorry but I realize now that i didn't understand your request.

From what I understand I think Magritte-Pharo7-Model adding the  'directory'   instance variable to MAExternalFileModel, and subdivides the various features related to the class itself:

a) MAFileSystem for the definition of file system management (it sender the asFileNameReference method)

b) MAFileDataBase for the management of the directories where to save the files and relative database cleaning

It is not very clear to me that the   'directory'   variable (set to aFileReference) has been added and because the  'location'  variable is no longer managed - referenced (so what is it for?)

So we have two possibilities:
1) keep the current basic version of Magritte-Gemstone-Model (which implements all the features) 

2) Re-implement for gemstone the new division of the functions defined in Magritte-Pharo7-Model

What do you think ?

**Comment by dalehenrich** [comment]
@dariogithub ... this looks like very helpful information, thanks a lot for digging into this for me  ... I will try to get back to magritte later today ....

**Comment by dalehenrich** [comment]
[This commit](https://github.com/dalehenrich/magritte/commit/9633944c96a5d0f937966bc65220b9d5a34cbc8b) addresses point **A)** in [this comment](https://github.com/magritte-metamodel/magritte/issues/105#issuecomment-489317514).

[This commit](https://github.com/glassdb/glass/commit/3b926e1d09e5aed5a0c9a24540617a7dcab8f4a3) implements AppendStream>>store:, whcih addresses point **B)** in [this comment](https://github.com/magritte-metamodel/magritte/issues/105#issuecomment-489317514).

**Comment by dalehenrich** [comment]
At this point, we have a collection of messages sent but not implemented:
```
--transcript--'Sent but not implemented from #''MADescriptionFlattener>>expandDescription:for:'''
--transcript--'#''groupExpandOnLabel'''
--transcript--'#''addToAccessor:'''
--transcript--'Sent but not implemented from #''Object>>isSameAs:using:'''
--transcript--'#''includesAll:'''
--transcript--'Sent but not implemented from #''MAPluggableAccessor>>storeBlock:on:'''
--transcript--'#''decompile'''
--transcript--'Sent but not implemented from #''MAStringReader>>visitBlockDescription:'''
--transcript--'#''compiler'''
--transcript--'Sent but not implemented from #''MADescription>>defaultCanExpand'''
--transcript--'#''tabDisplay'''
--transcript--'Sent but not implemented from #''MAActionDescription>>icon'''
--transcript--'#''iconNamed:'''
--transcript--'Sent but not implemented from #''MAFileDescription>>defaultDirectory'''
--transcript--'#''imageDirectory'''
--transcript--'Sent but not implemented from #''MAActionDescription>>selector:'''
--transcript--'#''deprecated:on:in:transformWith:'''
--transcript--'Sent but not implemented from #''MAMemento>>doesNotUnderstand:'''
--transcript--'#''detect:ifFound:'''
--transcript--'#''isMessage:'''
--transcript--'Sent but not implemented from #''MAActionDescription>>selector'''
--transcript--'#''deprecated:on:in:transformWith:'''
```
and a couple of undefined globals:
```
--transcript--'Undefined Symbol:#''QCDescriptionBuilderContainer'''
--transcript--'Undefined Symbol:#''MAFileSystem'''
--transcript--'Undefined Symbol:#''MAMemoMorph'''
```
Up until now, I've been able to draw upon classes that I had implemented in [Magritte3](https://github.com/GsDevKit/Magritte3) ... but none of the undefined globals above were implemented in Magritte3 ... **MAMemoMorph** can probably be bypassed, but no sure about **MAFileSystem** or **QCDescriptionBuilderContainer**.

I haven' gone through all of the sent but not implmented ... a number of them are probably related to the missing globals ... tonight I'll make a pass through the sent but not implemented and look for implementations in [Magritte3](https://github.com/GsDevKit/Magritte3).

@dariogithub, if you could look into **MAFileSystem** and **QCDescriptionBuilderContainer** to see if they apply to GemStone, that'd be helpful ... 

BTW, we have a port of [FileSystem](https://github.com/GemTalk/FileSystemGs) for GemStone 3.2.15 and 3.5.0, but the port is not quite complete ... it will be awhile (months?) before it is finished for 3.5.0 ...

**Comment by dariogithub** [comment]
QCDescriptionBuilderContainer  i believe it is no use and therefore can be bypassed.

In any case, keep in mind that, as i wrote the 6 May, in any case we must include one of the two solutions: 
1) keep the current basic version of Magritte-Gemstone-Model (which implements all the features)

2) Re-implement for gemstone the new division of the functions defined in Magritte-Pharo7-Model

In the Magritte-Model the MAFileSystem is only reference by the method:
   MAFileDescription defaultDirectory
        ^ self propertyAt: #defaultDirectory ifAbsent:[  MAFileSystem imageDirectory ]

 If we handle the first solution the question ( MAFileSystem ) can be bypassed.

**Comment by dalehenrich** [comment]
@dariogithub, Do you need the "new division of the functions defined in Magritte-Pharo7-Model"?

If not then we can defer additional work until such time that the functionality is needed for GemStone/Pharo users ...

Thanks for looking into MAFileSystem and QCDescriptionBuilderContainer ... I should be able to find time to do more work on magritte later today ...

**Comment by dariogithub** [comment]
The current basic version of Magritte-Gemstone-Model (which implements all the features) it's fine for now. Thanks

**Comment by dalehenrich** [comment]
With this commit (b35753f) all of the UndefinedSymbols have been resolved
