### ISSUE TITLE
There is no instruction to add it as dependency on the documentation

### ISSUE THREAD

**Issue by vitormcruz** [magritte-metamodel/magritte#108]
There is no documentation regarding to how should I add Magritte in my project as a dependency using Metacello.

**Comment by noha** [comment]
In your other issue you have to code snippet that is needed. How about adding it yourself to the README?

**Comment by vitormcruz** [comment]
I was not sure what was the correct code to add Magritte as a dependency to a project at the time I wrote this issues, I will assume that code snippet is correct then and will make a PR.
