### ISSUE TITLE
Can't define Magritte in Metacello

### ISSUE THREAD

**Issue by vitormcruz** [magritte-metamodel/magritte#109]
When I define Metacello in my project as a dependency:

`baseline: 'Magritte' with: [ spec repository: 'github://magritte-metamodel/magritte:v3.5.4'; loads: #(Core) ];`

I got the following error when trying to load my project:

> project group, or package named: 'Magritte-Tests-Pharo-Model' not found when used in requires: or includes: field of package: 'Magritte-Tests-Model' for version: baseline of BaselineOfMagritte.

**Comment by noha** [comment]
What is the image version you try to load into?

**Comment by vitormcruz** [comment]
8.0

In 7.0 it works.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by noha** [comment]
I don't think it is a good idea to load a stable version of magritte if you use unstable pharo. If you load master of magritte it should work.

**Comment by vitormcruz** [comment]
Yeah, I had not touch my Pharo projects in some months so when I did I tried the last version I saw on the Launcher :)

I confirm it works with Pharo 8 using master. I will close the issue.
