### ISSUE TITLE
Clean issues by closing old issues

### ISSUE THREAD

**Issue by noha** [magritte-metamodel/magritte#112]
Issues which are years old should be closed because no code was committed and noone showed interest. This issue is for discussing it.

**Comment by seandenigris** [comment]
Does this plugin address your concern, @noha ? I just copied what Pharo did to get us started but we can tweak if needed.

**Comment by noha** [comment]
Great initiative!! Thanks! We know it is a two hearted thing. Closing unsolved issue always feels like ignorance. But the code is always what it is and not perfect. So if nobody cares nobody needs it. I think it is a good way to deal. Furthermore because when I look at a project that has 4 year old issues I think nobody really cares anyway
