### ISSUE TITLE
Add descriptions for actions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [magritte-metamodel/magritte#15]
```
See http://forum.world.st/Model-actions-td4693208.html
```

Original issue reported on code.google.com by `sean.p.d...@gmail.com` on 25 Sep 2013 at 6:24

**Comment by seandenigris** [comment]
2ba7706 implemented fully reified `MAActionDescription`s. Per Lukas, the command pattern with meta-descriptions makes explicit support unneeded. Let's play with the current implementation and see how it goes. In order of ascending complexity:
1. Tagged methods - see comment above
2. Action descriptions (current approach)
3. Meta-described Commands
