### ISSUE TITLE
MADescriptionBuilder is in Two Packages

### ISSUE THREAD

**Issue by seandenigris** [magritte-metamodel/magritte#160]
It appears in both [`Magritte-Model`](https://github.com/magritte-metamodel/magritte/tree/master/source/Magritte-Model.package/MADescriptionBuilder.class) and [`Magritte-Deprecated`](https://github.com/magritte-metamodel/magritte/tree/master/source/Magritte-Deprecated.package/MADescriptionBuilder.class). What is the proper location? @delware @noha @NickAger

**Comment by seandenigris** [comment]
This is blocking Tonel migration (#159 and #157)

**Comment by noha** [comment]
Looks like Magritte-Model until MAContainer>>#descriptionBuilders: is not to deprecate. This method references a subclass of MADescriptionBuilder. So Model is ok we can deprecate later if needed

**Comment by seandenigris** [comment]
Fixed by 089a2bd
