### ISSUE TITLE
MARelationDescription reference fails on MADescription is abstract

### ISSUE THREAD

**Issue by pavel-krivanek** [magritte-metamodel/magritte#193]
MARelationDescription reference can, in the current value printing, raise an error: `MADescription is abstract`

## How to reproduce

- in `MADescriptionEditor>>#defaultDescription`, return 

```smalltalk
defaultDescription
	^ MAContainer new magritteDescription 
```
to have some more complex description to browse
- Go to to the Seaside editor: [http://localhost:8080/magritte/editor](http://localhost:8080/magritte/editor)
- go to the second page and edit the description named "Validation"
- `MAError: MADescription is abstract.`

**Comment by seandenigris** [comment]
Any idea for a fix? I'm afraid I don't exactly understand the use case. Can you quote or link to the calling code?

**Comment by pavel-krivanek** [comment]
I need to try to find a more easily reproducible case. The use case is to be able to edit meta-models using UI, I think it is the same for Magritte-Spec
