### ISSUE TITLE
reference related MAToOneRelationDescription storeString problems

### ISSUE THREAD

**Issue by pavel-krivanek** [magritte-metamodel/magritte#201]
Trying to create storeString for `MAToOneRelationDescription` for purpose of code generation creates a huge string and in my image, it even hangs Pharo. 

```smalltalk
MAToOneRelationDescription new storeString
```

The main problem is in reference. For relations, the default reference (`MARelationDescription class>>#defaultReference`) is `nil`. But then, it is replaced by a huge container.

I'm not really sure but maybe the best solution would be to use a special kind of MADescription for such undefined reference and do not use general `nil`

**Comment by pavel-krivanek** [comment]
The better solution seem to be to prevent relation descriptions to serialize their own description.

My very dirty ugly hack is to add method `MAReferenceDescription>>#storeOn:` as
```smalltalk
storeOn: aStream
	aStream 
		nextPutAll: self className;
		nextPutAll: ' new'; cr.
	(self magritteDescription reject: #isReadOnly) do: [ :desc |
		| value |
		value := desc read: self.
		((desc label ~= 'Description') and: [(value ~= desc default and: [ value isNotNil ])]) ifTrue: [ 
			desc accessor store: value inDescriptionOn: aStream ] ].
	aStream nextPutAll: 'yourself'
```

**Comment by seandenigris** [comment]
I've run into this and it is a pain, although I never had an image hang! Let's think a bit about a solution. The reference stuff has always baffled me no matter how many times I try to understand it...
