### ISSUE TITLE
cyclic dependenies in Magritte packages

### ISSUE THREAD

**Issue by pavel-krivanek** [magritte-metamodel/magritte#202]
Magritte-Model depends on Magritte-Morph, Magritte-Pharo7-Model, Magritte-Developer etc

**Comment by seandenigris** [comment]
Could you say more about which dependencies exactly are cyclical?

**Comment by pavel-krivanek** [comment]
Magritte-Model package must not have any dependency on any package depneds on it.

MABlockDescription  has dependency on MAMorphicMemo
MAFileDescription has dependency on MAFileSystem 
Magritte-Model package calls messaged defined in Magritte-Developer (storeVia:inDescriptionOn). This one reveals if you unload Magritte-Developer package

See the PR for details
