### ISSUE TITLE
Relationships with Primitives

### ISSUE THREAD

**Issue by seandenigris** [magritte-metamodel/magritte#22]
What if we want to have a `MAToManyRelationDescription` holding `ByteString`s? ByteString has no field descriptions and so can't be specified in `#classes:`.

`#asString` and `#copyFrom:` might be generally useful here. For URL's, maybe they could be set as the accessors for a `MAURLDescription`

**Comment by noha** [comment]
Ins‘t the multiple option description the one you use if you have a bunch of strings?

**Comment by seandenigris** [comment]
> Ins‘t the multiple option description the one you use if you have a bunch of strings?
Not necessarily. The options can be any kind of object, the distinction is that the set is prearranged (the metamodel also supports adding options) vs ToXyzRelationDescriptions where you create the objects on the fly.
