### ISSUE TITLE
MAElementRow error when MAToManyRelationDescription is used

### ISSUE THREAD

**Issue by JanBliznicenko** [magritte-metamodel/magritte#234]
Hello, commit 27e2944 made some changes to how strings are handled. Unfortunately, that change broke my code. I am not sure whether this is a bug in magritte or the code I maintain.

`MAElementRow` used to send `displayStringFor:` to the container description and was changed to use `toString:`. Unfortunately, this change caused that block set by `display:` is ignored and it causes, in my case, error `Instance of OPUmlGeneralizationSetDescriptions did not understand #do:separatedBy:` sent from that `MAStringWriter>>#visitToManyRelationDescription:`. OPUmlGeneralizationSetDescription is quite simple subclass of Object: https://github.com/OpenPonk/class-editor/blob/master/repository/OpenPonk-ClassEditor/OPUmlGeneralizationSetDescriptions.class.st

I do not know if I can and even should fix the issue. I am not the author of the Magritte use in the project and do not have very good knowledge of Magritte either.

Steps to reproduce my specific issue require loading our (quite large) OpenPonk project:
1.  Load OpenPonk project with UML Class editor plugin in Pharo 9:
```
Metacello new
		baseline: 'OpenPonk';
		repository: 'github://openponk/openponk:8a943f839';
		lock;
		load.
Metacello new
		baseline: 'ClassEditor';
		repository: 'github://openponk/class-editor';
		onConflictUseLoaded;
		load.
```
2. Open the OpenPonk with form that uses Magritte:
```
| workbench controller |
OPUmlExamples exampleGeneralizationSets.
workbench := OPWorkbench allInstances last.
controller := workbench focusedEditor diagramController controllers detect: [ :any | any isKindOf: OPUmlGeneralizationController ].
workbench openFormOn: controller.
```
Note that this step usually means multiple manual clicking.

3. Click on "Edit" button in the middle right.

Originally, it opened form with details of the generalization in new window.
Since the mentioned commit, error is thrown instead.
To load the working version with older Magritte, replace the commit hash in Metacello loading script to `8b835c5`

Thank you.

**Comment by JanBliznicenko** [comment]
Issue is still present and I had to keep OpenPonk on older Magritte version

**Comment by seandenigris** [comment]
Thanks for the bump. I’ll look into it. Any way you can give a simple example to reproduce without loading additional projects?

**Comment by seandenigris** [comment]
@JanBliznicenko would you confirm this solves your problem?

**Comment by JanBliznicenko** [comment]
Hello, sorry for taking so long with testing the solution. Yes, it seems you fixed my problem, thank you very much :)

**Comment by seandenigris** [comment]
Great news. Thanks for confirming
