### ISSUE TITLE
requiresMultipartForm is nil walkback, probably being triggered by MAInternalEditorComponent  

### ISSUE THREAD

**Issue by sanjayminni** [magritte-metamodel/magritte#243]
MAInternalEditorComponent is throwing an error (P9+win64).
I am trying out the examples in magritte booklet and this walkback appears: 
MessageNotUnderstood: receiver of "requiresMultipartForm" is nil, probably due to use of CMPerson>>descriptionHomeAddress

I also find this error mentioned in magritte-wip.pdf pg 38
"SD: check because when pressing on editView I got a ”requiresMultipartForm” is nil"

![MagritteErr](https://user-images.githubusercontent.com/12030766/140856853-9e599f23-aca3-4203-8daa-e9fb4444b3f7.jpg)

![image](https://user-images.githubusercontent.com/12030766/140856931-5a339180-3f15-44c0-950c-9bd9ddea4814.png)

**Comment by sanjayminni** [comment]
it still isn't working but the error message / walkback has changed
![MAInternalComponent](https://user-images.githubusercontent.com/12030766/144818586-8efd3c84-47f6-4225-bcd7-b493a6cc8500.jpg)

**Comment by StephanEggermont** [comment]
Is that object initialized? Looks like nil from here

**Comment by sanjayminni** [comment]
I checked with initialising as follows: 
I have CMPerson calling MAInternalEditor with CMAddress and CMAddress only has 1 variable <street> with description MAStringDescription
 
 Approach A
A.  CMPerson>>descriptionHomeAddress
 	^ MAToOneRelationDescription new
			componentClass: MAInternalEditorComponent;
			classes: (Array with: CMAddress);
			accessor: #homeAddress;
			label: 'Home Address';
			**default: CMAddress new;**         _this led to a crash seaside crash message in browser as per below_
			yourself

    ![MAInternalComponent-withDefault](https://user-images.githubusercontent.com/12030766/144890957-52644dea-8c17-4bbc-97c3-0966fdb68f62.jpg)

Approach  B
B. CMAddress>>descriptionStreet 
   initialised the variable in the called component using "default:" in the description
   ^ MAStringDescription new
		accessor: #street;
		label: 'Street';
		default: 'abc';
		yourself
   ![MAInternalComponent-StreetDefault](https://user-images.githubusercontent.com/12030766/144893338-a369d2a7-50d8-4608-b561-d3c3f8bcade7.jpg)

Approach C
C CMAddress>>initialize
          street := 'abc'.

![MAInternalComponent-InitializeStreet](https://user-images.githubusercontent.com/12030766/144893788-d108a1e3-7dbf-4165-9fe2-f10737151146.jpg)

**Comment by StephanEggermont** [comment]
CMPerson>>#initialize
 homeAddress := CMAddress new

?

**Comment by sanjayminni** [comment]
no did not work,
initialised as above and changed in >>descriptionHomeAddress from - ... classes: (Array with: CMAddress) - to - ... classes: (Array with: homeAddress) 
I have attached the package to this reply - its very simple. Entry point is  MAPersonManager initialize

[Magritte-ContactManager.zip](https://github.com/magritte-metamodel/magritte/files/7665606/Magritte-ContactManager.zip)

**Comment by StephanEggermont** [comment]
Hmm. Bot is broken
