### ISSUE TITLE
Support: Best way to make "action" button

### ISSUE THREAD

**Issue by JanBliznicenko** [magritte-metamodel/magritte#245]
Hello, I want to create a complex action that does not relate to any specific value of any attribute. Specificially, this action switches two items contained within the model object. Currently, I use MABooleanDescription with accessor reading always false and write doing the action. Is there any way to present the action as button, or have some icon there or something like that instead of checkbox that is always unchecked? I noticed existence of MAActionDescription, but I am not sure how to use it since it is not compatible with MADescription (completely different methods).

Thank you

**Comment by seandenigris** [comment]
Is your UI Morphic? Seaside?

**Comment by JanBliznicenko** [comment]
Hello, sorry for the delay. The UI si Morphic, it is for our OpenPonk tool, we use Pharo 9 and Spec 1.
![2022-02-04 (2)_LI](https://user-images.githubusercontent.com/9571633/152525778-5ea40931-afb0-4523-9b35-0aa6543835c7.jpg)

**Comment by seandenigris** [comment]
The pragma is `< magritteActionDescription>. Here is an example:
```smalltalk
Object>>#descriptionFuelOut
	<magritteActionDescription>
	^ MAActionDescription new	
			action: #fuelOut;
			priority: 1200;
			comment: 'Fuel Out';
			icon: #smallSave;
			yourself
```
