### ISSUE TITLE
ToOne Morph -> Infinite Resursion

### ISSUE THREAD

**Issue by seandenigris** [magritte-metamodel/magritte#25]

**Comment by seandenigris** [comment]
Addressed by Magritte-Model-SeanDeNigris.465 & Magritte-Morph-SeanDeNigris.95
[WIP]: Hack to make ToOne Morphs work i.e. stop infinite recursion, by duplicating ToMany logic (for now).

**Comment by noha** [comment]
If this is done please close

**Comment by seandenigris** [comment]
Seems to be fixed by 7d7f3e1
