### ISSUE TITLE
Extensible Reference Description Morph

### ISSUE THREAD

**Issue by seandenigris** [magritte-metamodel/magritte#28]
There is not a viable control for the use case where you are choosing between several likely known options, but may also select an unknown object that was not part of the initial options. For example, when tagging people in a photos, you'd want to start with known people, but be able to add new people too.

**Comment by seandenigris** [comment]
[Here is a screencast](https://www.youtube.com/watch?v=dV9_Z12G2Y0) of the new feature in action.

**Comment by noha** [comment]
Is done? Please close!
