### ISSUE TITLE
Magritte-Morph uses classes/method not in Pharo 10+

### ISSUE THREAD

**Issue by JanBliznicenko** [magritte-metamodel/magritte#294]
Magritte-Morph uses many classes and method that are not present in Pharo10+, so it does not work in many cases in Pharo 10+.

References to Spec1 classes that could probably be replaced by direct morph usage:
- [ ] MAMorphicDropList>>#buildMorphView uses DropListModel from Spec1
- [ ] MAMorphicDate>>#buildMorphView uses DateModelfrom Spec1
- [ ] TokenCollectorMorph>>#textInput uses TextInputFieldModel from Spec1

MAMorphicInternalEditor and MAMorphicExternalEditor use some methods that probably exist in Seaside (?), but Seaside is not requirement of Magritte-Morph and I am not sure why these methods are here. These are the references:
- [ ] MAMorphicInternalEditor>>#renderViewerOn: uses non-existent method isReadOnly
- [ ] MAMorphicInternalEditor>>#buildComponent uses non-existent method asComponentOn:
- [ ] MAMorphicExternalEditor>>#renderButtonsOn: uses non-existent method on:of:
- [ ] MAMorphicExternalEditor>>#renderViewerOn:: uses non-existent method reference

And few more things:
- [ ] MAElementRow>>#value: uses non-existent method memento
- [ ] MAContainer>>#elementBuilderFor: is unused and references non existing method

**Comment by seandenigris** [comment]
I have no experience with Spec 2 but would welcome a PR

**Comment by JanBliznicenko** [comment]
It seems Spec2 cannot replace the functionality here very well, it would be better to directly create Morphs. I have done it for MAMorphicDropList (currently just in my fork) that was the only problem here that caused errors for my use-cases. I will try to do the same for MAMorphicDate, but I am not sure what is even the purpose of TokenCollectorMorph so I don't know how to try it out. Could you provide me with some kind of executable example that would use the TokenCollectorMorph?

I have also found few more potential problems and added them to the original issue description.

**Comment by seandenigris** [comment]
Thanks! I don't think the Morphic stuff is tested very well, if at all. Did you test your fixes manually?

BTW in answer to your previous question, `TokenCollectorMorph` is an easy way to add ToManyRelation targets. It was inspired by GT's tag control:

<img width="1318" alt="Screen Shot 2022-08-26 at 3 29 40 PM" src="https://user-images.githubusercontent.com/184176/186978043-2a53c442-f284-4b70-bf8b-a7a0730345cb.png">

It looks like this in GT:

<img width="780" alt="Screen Shot 2022-08-26 at 3 26 34 PM" src="https://user-images.githubusercontent.com/184176/186977883-9183dbec-03b3-4b7b-abcf-06059340a42c.png">
