### ISSUE TITLE
error when loading v3.8

### ISSUE THREAD

**Issue by Ducasse** [magritte-metamodel/magritte#309]
Loading version v3.8 also leads to an error.

**Comment by Ducasse** [comment]
![Capture 2022-10-08 at 14 43 59](https://user-images.githubusercontent.com/432549/194708210-f8e1bf63-1470-4309-960d-70b22988fd92.png)

**Comment by seandenigris** [comment]
Thanks for the report. I'll have a look...

**Comment by seandenigris** [comment]
What happens if you load without specifying a version? I've been loading that way without problems in P10. Is it important for prior versions to work?

**Comment by Ducasse** [comment]
I do not know. I do not a sliding version.

**Comment by seandenigris** [comment]
What is the load script you used when you got that error?

**Comment by Ducasse** [comment]
It was a project that was apparently badly packaged. So I cannot reproduce it outside of it. So I will close it

**Comment by seandenigris** [comment]
Okay, let me know if you have any further problems. If the project is public, I can have a look if it would be helpful...
