### ISSUE TITLE
Package Dependency Warning

### ISSUE THREAD

**Issue by vitormcruz** [magritte-metamodel/magritte#31]
I am getting the error message while trying to load magritte throught the Pharo5 Catalog on a Windows machine:

"This package depends on the following classes:
  GRPharoPlatform
You must resolve these dependencies before you will be able to load these definitions: 
  GRPharoPlatform>>#magritteAllSubInstancesOf:do:
  GRPharoPlatform>>#magritteClassNamed:
  GRPharoPlatform>>#magritteColorClass
  GRPharoPlatform>>#magritteEvaluatorClassFor:
  GRPharoPlatform>>#magritteTimeStampClass
  GRPharoPlatform>>#magritteTimeStampIfAbsent:
  GRPharoPlatform>>#magritteUniqueObject

Select Proceed to continue, or close this window to cancel the operation."

Should this be provided as Magritte Project Dependencies?

**Comment by seandenigris** [comment]
I think this is not a problem as of Pharo 6.1, so we'll close for now.
