### ISSUE TITLE
[GT Search]: Transform should Accept Receiver Argument

### ISSUE THREAD

**Issue by snrnyc** [magritte-metamodel/magritte#317]
It would be nice because it would decouple the receiver from the description, which is a best practice because theoretically descriptions can be applied to any model object, so self can't be cached e.g. in a block. Then MATokenSelectorElement's initialize could `#cull:cull:`.

However, this causes an error if using mementos because there doesn't seem to be a way to pass the message through to the model object

**Comment by seandenigris** [comment]
Tried to have:
```smalltalk
gtSearchTransform: aValuable
	"aValuable - two optional parameters:
		- the model object (needed because theoretically descriptions can be applied to any model object, so self can't be cached e.g. in a block); this is annoyingly (because often you don't need it) the first argument because we want to be able to pass a selector here, which requires the receiver first
		- the object returned by the Search (already transformed by its send block if present)"

	self propertyAt: #gtSearchTransform put: aValuable
```

But had to roll back to "search result only" do to memento issue
