### ISSUE TITLE
MAContainer not working with pragmas - regression by changes from GToolkit

### ISSUE THREAD

**Issue by JanBliznicenko** [magritte-metamodel/magritte#337]
Since https://github.com/magritte-metamodel/magritte/commit/9842df75c0f5e728d76892fa0f3b55bdd1f6b840, descriptions using `MA(Priority)Container` no longer work, because not all description classes implement `definingContext:` 
sent by `MAPragmaBuilder>>#setDefiningContextOf:to:in:`
sent by `MAPragmaBuilder>>#buildDescriptions:`

I believe `definingContext:` should be implemented by `MADescription` (or defined as subclass responsibility and implemented in `MAContainer` as well).

![obrazek](https://github.com/magritte-metamodel/magritte/assets/9571633/b3dda308-9e7f-4763-90ab-3ebf801ab989)

**Comment by seandenigris** [comment]
Thanks for the report. That's probably my fault. I vaguely remember that it was originally implemented in the superclass. So I fully understand, what is the scenario that causes the error? The tests are all passing, so we should also add a test for that use case.

**Comment by JanBliznicenko** [comment]
```
Object subclass: #MAMockWithContainer
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Magritte-Tests-Model-Mocks'.

(Smalltalk at: #MAMockWithContainer) compile: 'descriptionWithContainer
	<magritteDescription>
	^ MAContainer new'.

(Smalltalk at: #MAMockWithContainer) new magritteDescription.
```

However, when I look at other usages of MAContainer, they seem to be always used as `<magritteContainer>`, not as `<magritteDescription>`, even if they **are** descriptions (subclass of `MADescription`)

**Comment by seandenigris** [comment]
I was thinking that I hadn't seen containers used that way. Do you have a use case that is not supported by the existing behavior?

**Comment by JanBliznicenko** [comment]
You are right that I might not be using the containers correctly and this was more of a coincidence that it used to work.
