### ISSUE TITLE
Add pharo 7 support

### ISSUE THREAD

**Issue by noha** [magritte-metamodel/magritte#41]
Pharo 7 should be supported by magritte

**Comment by noha** [comment]
There is a pull request integrating it: https://github.com/magritte-metamodel/magritte/pull/39

**Comment by noha** [comment]
Tests are green but the baseline of magritte references master on grease which is not good. As soon as there is a new grease release the baseline should be fixed to the new version and the PR should be merged

**Comment by StephanEggermont** [comment]
branch or tag?

**Comment by noha** [comment]
If you don‘t phrase a proper question I cannot help
