### ISSUE TITLE
When readonly: true a component should not display its comments.

### ISSUE THREAD

**Issue by Ducasse** [magritte-metamodel/magritte#88]
I have a Seaside Magritte application for the TinyBlogTutorial book.

Now when my component is in readonly mode I do not want to see the comments such as “please enter text” (below).

Apparently the frameworks is handling that correctly since I read:

renderContentOn: html
	self isReadonly
		ifTrue: [ self renderViewerOn: html ]
		ifFalse: [ self renderEditorOn: html ]

and my code is so I correctly set the readonly property

viewPost: aPost
	self call: (self renderViewPostForm: aPost)

renderViewPostForm: aPost
	^ aPost asComponent
		addDecoration: (TBSMagritteFormDecoration buttons: {(#cancel -> 'Back')});
		readonly: true;
		yourself

This is for TinyBlog, the code can be loaded doing

./loadSolutionForChapter.sh 9

![screen shot 2018-08-20 at 21 07 34](https://user-images.githubusercontent.com/432549/44361770-33d36180-a4bf-11e8-9e8a-3ee5e54ee8c7.png)

**Comment by Ducasse** [comment]
it looks like renderElement in TBSMagritteFOrmRender is bogus

renderElement: aDescription
	aDescription group = group
		ifFalse: [ self renderGroup: aDescription ].
		
	html tbsFormGroup
		class: (self classFor: aDescription);
		with: [
			| tag |
			self renderLabel: aDescription.
			tag := html div
				class: 'controls';
				yourself.
			self formHorizontal ifTrue: [ tag class: 'col-sm-10' ].
			tag
				with: [ 
					self renderControl: aDescription.
					self renderComment: aDescription.
					self validationMessagesInline ifTrue: [ self renderInlineError: aDescription ] ] ]

Since it renders blindly comments in renderComment:

**Comment by Ducasse** [comment]
My solution is that one

renderElement: aDescription
	aDescription group = group
		ifFalse: [ self renderGroup: aDescription ].
		
	html tbsFormGroup
		class: (self classFor: aDescription);
		with: [
			| tag |
			self renderLabel: aDescription.
			tag := html div
				class: 'controls';
				yourself.
			self formHorizontal ifTrue: [ tag class: 'col-sm-10' ].
			tag
				with: [ 
					self renderControl: aDescription.
					component isReadonly ifFalse: [ self renderComment: aDescription].
					self validationMessagesInline ifTrue: [ self renderInlineError: aDescription ] ] ]

**Comment by Ducasse** [comment]
I just renderComment: only if the component is in edit mode.

**Comment by Ducasse** [comment]
Now I do not know how to get this fix integrated in Magritte

**Comment by astares** [comment]
Included in STHub version in http://smalltalkhub.com/mc/TorstenBergmann/BootstrapMagritte/main
________________________________________________________________________________
Name: Bootstrap-Magritte-Core-TorstenBergmann.16
Author: TorstenBergmann
Time: 21 August 2018, 10:23:44.406132 pm
UUID: 74c6198a-5930-0d00-9925-e0ac0faa47a9
Ancestors: Bootstrap-Magritte-Core-EstebanMaringolo.15

Do not render comments for readOnly components
Fix done for Stef to provide a new book.

Details in https://github.com/magritte-metamodel/magritte/issues/88
________________________________________________________________________________

**Comment by noha** [comment]
I consider this as done somewhere else
