### ISSUE TITLE
isReadonly is not defined in MADescriptionMorph hierarchy

### ISSUE THREAD

**Issue by Ducasse** [magritte-metamodel/magritte#89]
There MAListMorph >> renderViewerOn: html
	html render: (self component
		readonly: self isReadonly;
		yourself)

cannot work

**Comment by seandenigris** [comment]
Is `self description isReadOnly` not enough, @Ducasse?

NB. `readonly` has been changed in Magritte to `readOnly` to be proper English and consistent with Pharo
