### ISSUE TITLE
[Bug]: DNU on the Form tab on the GT-Inspector on MAContainerComponent

### ISSUE THREAD

**Issue by edcrypt** [magritte-metamodel/magritte#93]
```
address := Address new street: 'foo'; yourself.
address asComponent inspect
```
- Click on the Form tab
- Result: DNU #street (it passes the MAContainerComponent as model)

I think it's not the same as #42, sorry If duplicate.
I'm using Pharo7RC1 and the most recent Magritte.

**Comment by Ducasse** [comment]
Thanks for the report. I'm quite busy right now.
