### ISSUE TITLE
Is there a reason to have so many groups from Seaside?

### ISSUE THREAD

**Issue by jecisc** [magritte-metamodel/magritte#94]
I wonder if we really need all those groups from Seaside:

https://github.com/magritte-metamodel/magritte/blob/master/source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline310CommonExtDeps..st

I have the impression we only need 'Core'. If a user of Magritte needs RSS, Welcome, etc it's his responsibility, not the one of Magritte. I was surprise to find RSS, Welcome, FileSystem in my image after loading a project depending on Magritte.

**Comment by noha** [comment]
Agreed
